### ISSUE TITLE
Remove dependency on react-rails

### ISSUE THREAD

**Issue by patrickclery** [patrickclery/dry-rails-react#91]
As a developer, I'd like to be able to...
- [ ] Auth with JWT (#92)
- [ ] Use webpack without the webpacker layer
- [ ] Deploy frontend and API separately

### Action Steps

- [ ] Create a separate folder using CRA
- [ ] Test that a working App component loads (before swapping in old ones)
- [ ] Migrate all old components to new CRA
- [ ] Add script to start puma + webpack-dev-server (foreman)
- [ ] Deploy on Heroku with separated concerns
- [ ] Remove react-rails and all UI/JavaScript related code

_Biggest challenge_ will be serving the files without having a controller for index.html

Currently, react/rails are coupled in that even the index.html must be served from Rails via Webpacker. I would like the Rails APi to be a pure JSON API without any coupling to Webpack.
